### ISSUE TITLE
Update README demo

### ISSUE THREAD

**Issue by gerverska** [brendanf/LSUx#5]
Hi Brendan! Small issue, but the first three **Usage** code blocks refer to `fungal_32S.cm`, `fungal_32S_LR5.cm`, and their `.stk` equivalents. It seems the actual files are prefixed with `fungi` instead of `fungal`. Downstream code blocks look correct, though. Just figured I'd mention here to keep your inbox clean!

**Comment by brendanf** [comment]
Fixed in 1423e2d

Thanks Kyle!
